SELECT ITEM_ID, ITEM_NAME, RARITY
  FROM ITEM_INFO A
  JOIN ITEM_TREE B
 USING (ITEM_ID)
 WHERE NOT EXISTS (
    SELECT 1
      FROM ITEM_TREE AA
     WHERE AA.PARENT_ITEM_ID = A.ITEM_ID
 )
 ORDER BY 1 DESC