SELECT ID, SUM(C) CHILD_COUNT
  FROM (SELECT A.ID, COUNT(B.ID) C
          FROM ECOLI_DATA A
          LEFT OUTER JOIN ECOLI_DATA B
          ON A.ID = B.PARENT_ID
          GROUP BY A.ID, B.ID) A
GROUP BY ID