SELECT AA.ITEM_ID, ITEM_NAME, RARITY
  FROM (SELECT B.ITEM_ID
          FROM ITEM_INFO A
          RIGHT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
         WHERE A.RARITY = 'RARE') AA
  JOIN ITEM_INFO BB ON AA.ITEM_ID = BB.ITEM_ID
ORDER BY 1 DESC